import {afterEach, beforeEach, describe, expect, it, vi} from 'vitest'
import {mkdtemp, cp, readFile, writeFile, readdir, rm} from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import {Engine} from '../src/main/engine'
import {Storage} from '../src/main/storage'
import {loadLibrary} from '../src/main/library'
import {allQuizzes, nextReview} from '../src/shared/study'
import {correctAnswer} from '../src/shared/scoring'
import type {Session} from '../src/shared/schema'
let root: string, library: string, dataDir: string, engine: Engine
beforeEach(async () => {root = await mkdtemp(path.join(os.tmpdir(), 'quizmeadow-test-')); library = path.join(root, 'library'); dataDir = path.join(root, 'data'); await cp('library', library, {recursive: true}); engine = new Engine(new Storage(dataDir), library, 'test'); await engine.initialize()})
afterEach(async () => {vi.useRealTimers(); await rm(root, {recursive: true, force: true})})
async function start(mode: 'practice' | 'exam' = 'practice', minutes?: number) {const quiz = allQuizzes((await engine.bootstrap()).library).find(q => q.id === 'all-types')!; return engine.start({quizKeys: [quiz.key], mode, source: 'quiz', count: 500, shuffle: false, timeLimitMinutes: minutes})}
function answered(session: Session): Session {return {...session, responses: Object.fromEntries(session.questions.map(q => [q.key, {answer: correctAnswer(q.question), timeMs: 1000, confidence: 'high', selfAssessment: 'rubric' in q.question ? q.question.rubric.map(r => r.id) : undefined}]))}}
describe('persistent study sessions', () => {
 it('loads all formats and starts with no invented progress', async () => {const data = await engine.bootstrap(); expect(data.attempts).toEqual([]); expect(data.library.issues).toEqual([]); expect(allQuizzes(data.library).reduce((n, q) => n + q.questions.length, 0)).toBe(10); expect(data.session).toBeNull()})
 it('resumes saved responses and question ordering after a restart', async () => {const s = await start(); s.responses[s.questions[0].key] = {answer: 'four', confidence: 'medium', timeMs: 1200}; s.currentIndex = 1; await engine.save(s); const restarted = new Engine(new Storage(dataDir), library, 'test'); await restarted.initialize(); expect((await restarted.bootstrap()).session).toEqual({...s, updatedAt: expect.any(String)})})
 it('requires a saved session to be resumed or discarded before replacement', async () => {await start(); await expect(start()).rejects.toThrow('Resume or discard'); const s = (await engine.bootstrap()).session!; await engine.discard('wrong-id'); expect((await engine.bootstrap()).session).not.toBeNull(); await engine.discard(s.id); expect((await engine.bootstrap()).session).toBeNull()})
 it('persists weighted scores and distinguishes self-assessment', async () => {const s = answered(await start()); const a = await engine.finish(s); expect(a.percent).toBe(100); expect(a.earned).toBe(27); expect(a.grades.filter(g => g.grading === 'self')).toHaveLength(2); expect((await engine.bootstrap()).session).toBeNull(); expect((await engine.bootstrap()).attempts).toHaveLength(1)})
 it('makes repeated finish requests idempotent', async () => {const s = answered(await start()); const a = await engine.finish(s); expect((await engine.finish(s)).id).toBe(a.id); expect((await engine.bootstrap()).attempts).toHaveLength(1)})
 it('repairs review state after an interrupted completion without extending intervals twice', async () => {const s = answered(await start()); const a = await engine.finish(s); const first = (await engine.bootstrap()).reviews; await writeFile(path.join(dataDir, 'reviews.json'), JSON.stringify({schemaVersion: 1, data: []})); await engine.finish(s); expect((await engine.bootstrap()).reviews).toEqual(first); await engine.finish(s); expect((await engine.bootstrap()).reviews).toEqual(first)})
 it('prevents renderer payloads from altering grading rules', async () => {const s = await start(); const changed = structuredClone(s); changed.questions[0].question.points = 999; changed.questions[0].question.prompt = 'Tampered'; changed.responses[changed.questions[0].key] = {answer: 'four', timeMs: 0}; const a = await engine.finish(changed); expect(a.questions[0].question.points).toBe(1); expect(a.questions[0].question.prompt).toBe('What is 2 + 2?'); expect(a.possible).toBe(27)})
 it('preserves a finished content snapshot after library edits', async () => {const s = answered(await start()); const a = await engine.finish(s); const file = path.join(library, 'question-lab/01-formats/all-types.yaml'); await writeFile(file, (await readFile(file, 'utf8')).replace('What is 2 + 2?', 'What is two plus two?')); const current = await engine.refresh(); expect(allQuizzes(current.library).find(q => q.id === 'all-types')!.revision).not.toBe(a.questions[0].revision); expect(current.attempts[0].questions[0].question.prompt).toBe('What is 2 + 2?')})
 it('locks checked practice answers while allowing rubric updates', async () => {const s = await start(); const key = s.questions[0].key; s.responses[key] = {answer: 'three', checked: true, timeMs: 0}; await engine.save(s); s.responses[key].answer = 'four'; expect((await engine.finish(s)).grades[0].earned).toBe(0)})
 it('freezes answers at the exam deadline across restarts', async () => {vi.useFakeTimers({toFake: ['Date']}); vi.setSystemTime(new Date('2026-09-29T10:00:00Z')); const s = await start('exam', 1); const key = s.questions[0].key; s.responses[key] = {answer: 'three', timeMs: 0}; await engine.save(s); vi.setSystemTime(new Date('2026-09-29T10:01:01Z')); const restarted = new Engine(new Storage(dataDir), library, 'test'); await restarted.initialize(); s.responses[key].answer = 'four'; const a = await restarted.finish(s); expect(a.grades[0].earned).toBe(0)})
 it('freezes answer text during self-assessment', async () => {const s = answered(await start('exam')); s.phase = 'grading'; await engine.save(s); const key = s.questions[0].key; s.responses[key].answer = 'three'; const a = await engine.finish(s); expect(a.grades[0].earned).toBe(1)})
 it('keeps valid quizzes available when another YAML file is malformed', async () => {await writeFile(path.join(library, 'question-lab/01-formats/broken.yaml'), 'invalid: ['); const current = await loadLibrary(library); expect(current.issues).toHaveLength(1); expect(allQuizzes(current)).toHaveLength(1)})
 it('rejects YAML aliases instead of expanding them', async () => {await writeFile(path.join(library, 'question-lab/01-formats/aliases.yaml'), 'a: &a [a]\nb: *a'); const current = await loadLibrary(library); expect(current.issues).toHaveLength(1)})
 it('warns about corrupt session data and backs it up before replacement', async () => {await start(); await writeFile(path.join(dataDir, 'session.json'), '{broken'); const data = await engine.bootstrap(); expect(data.warnings.join(' ')).toContain('session.json'); expect(data.session).toBeNull(); await start(); const names = await readdir(dataDir); const backup = names.find(n => n.startsWith('session.json.backup-'))!; expect(await readFile(path.join(dataDir, backup), 'utf8')).toBe('{broken')})
})
describe('spaced review scheduling', () => {
 it('returns incorrect or uncertain answers soon and extends confident recall', () => {const now = new Date('2026-09-29T10:00:00Z'); expect(nextReview(undefined, false, 'high', 'q', 'r', now).intervalDays).toBe(1); expect(nextReview(undefined, true, 'low', 'q', 'r', now).intervalDays).toBe(1); const first = nextReview(undefined, true, 'high', 'q', 'r', now); expect(nextReview(first, true, 'high', 'q', 'r', now).intervalDays).toBeGreaterThan(first.intervalDays)})
})
