import {ArrowRight, BookOpen, Clock3, Play, Target, TrendingUp} from 'lucide-react'
import type {Bootstrap, Category, LibraryQuiz} from '../shared/schema'
import {allQuizzes, latestOutcomes} from '../shared/study'
import {Page, Pill, formatDate} from './ui'
export function Dashboard({data, onLibrary, onStart, onResume, onReview, due, mistakes}: {data: Bootstrap; onLibrary: (id?: string) => void; onStart: (q: LibraryQuiz) => void; onResume: () => void; onReview: () => void; due: number; mistakes: number}) {
 const quizzes = allQuizzes(data.library), total = quizzes.reduce((n, q) => n + q.questions.length, 0), latest = latestOutcomes(data.attempts)
 const known = quizzes.flatMap(q => q.questions.map(question => ({key: `${q.key}/${question.id}`, revision: q.revision}))).filter(q => latest.get(q.key)?.attempt.questions[latest.get(q.key)!.index].revision === q.revision)
 const correct = known.filter(q => {const v = latest.get(q.key)!; return v.attempt.grades[v.index].correct}).length
 const now = new Date(), start = new Date(now); start.setHours(0, 0, 0, 0); start.setDate(start.getDate() - ((start.getDay() + 6) % 7))
 const weekly = data.attempts.filter(a => Date.parse(a.completedAt) >= start.getTime()).length
 const days = Array.from({length: 7}, (_, i) => {const d = new Date(start); d.setDate(d.getDate() + i); return {d, count: data.attempts.filter(a => new Date(a.completedAt).toDateString() === d.toDateString()).length}})
 const average = data.attempts.length ? data.attempts.reduce((n, a) => n + a.percent, 0) / data.attempts.length : null
 const next = quizzes.find(q => !data.attempts.some(a => a.questions.some(sq => sq.quizKey === q.key))) ?? quizzes[0]
 const coverage = (category: Category) => {const items = category.units.flatMap(u => u.quizzes.flatMap(q => q.questions.map(question => ({key: `${q.key}/${question.id}`, revision: q.revision})))); const done = items.filter(q => {const v = latest.get(q.key); return v && v.attempt.questions[v.index].revision === q.revision}); return items.length ? Math.round(done.length / items.length * 100) : 0}
 return <Page><div className="page-heading"><div><div className="eyebrow">TODAY</div><h1>Make it stick.</h1><p>Small sessions. Deeper understanding. Progress you can see.</p></div><Pill tone="green"><span className="status-dot"/>Offline & private</Pill></div>
 {data.session && <button className="resume-banner" onClick={onResume}><span className="resume-icon"><Play size={19}/></span><div><strong>Pick up where you left off</strong><span>{data.session.title} · {Object.keys(data.session.responses).length}/{data.session.questions.length} answered</span></div><span className="button small primary">Resume<ArrowRight size={16}/></span></button>}
 <section className="study-next"><div><div className="eyebrow">{due ? 'SPACED REVIEW' : 'NEXT SESSION'}</div><h2>{due ? 'Bring it back to mind' : next?.title || 'Connect your study library'}</h2><p>{due ? `${due} questions are ready for a spaced review.` : next ? `${next.questions.length} questions · ${next.unitTitle} · Practice or exam` : 'Choose a folder in Settings & data to get started.'}</p></div><button className="button primary" disabled={!next} onClick={() => due ? onReview() : next && onStart(next)}>{due ? 'Review what’s due' : 'Start a session'}<ArrowRight size={17}/></button></section>
 <div className="stats-grid"><Stat icon={<Target size={18}/>} label="Questions explored" value={`${known.length}`} suffix={`/ ${total}`} detail="Current library coverage"/><Stat icon={<TrendingUp size={18}/>} label="Average score" value={average === null ? '—' : `${Math.round(average)}%`} detail={`${data.attempts.length} completed ${data.attempts.length === 1 ? 'session' : 'sessions'}`}/><Stat icon={<BookOpen size={18}/>} label="Recalled correctly" value={`${correct}`} detail="Latest result per current question"/><Stat icon={<Clock3 size={18}/>} label="Ready for review" value={`${due}`} detail={`${mistakes} questions to revisit`}/></div>
 <div className="dashboard-bottom"><section><div className="section-heading"><h2>Your courses</h2><button className="text-link" onClick={() => onLibrary()}>View library<ArrowRight size={14}/></button></div><div className="course-grid">{data.library.categories.map(c => <button key={c.id} className="course-card bgp-card" onClick={() => onLibrary(c.id)}><div className="bgp-card-head"><span>{c.units.length} {c.units.length === 1 ? 'unit' : 'units'}</span><span>{c.units.reduce((n, u) => n + u.quizzes.length, 0)} {c.units.reduce((n, u) => n + u.quizzes.length, 0) === 1 ? 'quiz' : 'quizzes'}</span></div><div className="bgp-card-body"><h3 className="bgp-card-title">{c.title}</h3><p>{c.description || 'Build understanding, one unit at a time.'}</p><div className="course-progress" role="progressbar" aria-label={`${c.title} coverage`} aria-valuenow={coverage(c)} aria-valuemin={0} aria-valuemax={100}><span style={{width: `${coverage(c)}%`}}/></div></div><div className="bgp-card-foot"><span>{coverage(c)}% explored</span><span className="row">Open course<ArrowRight size={17}/></span></div></button>)}</div>{!data.library.categories.length && <div className="callout">Choose a study library in Settings to get started.</div>}</section><aside className="week-card bgp-panel"><div className="row spread"><h3>This week</h3><Target size={18}/></div><div className="weekly-number">{weekly}<span> / {data.settings.weeklyGoal} sessions</span></div><div className="week-days">{days.map(({d, count}) => <div key={d.toISOString()}><span className={`${count ? 'active' : ''} ${d.toDateString() === now.toDateString() ? 'today' : ''}`} title={`${formatDate(d.toISOString())}: ${count} sessions`}>{count ? <CheckMark/> : d.getDate()}</span><small>{d.toLocaleDateString(undefined, {weekday: 'narrow'})}</small></div>)}</div><div className="divider"/><p>{weekly >= data.settings.weeklyGoal ? 'You met your weekly goal. Keep it sustainable.' : 'A short session counts. Aim for understanding, then come back tomorrow.'}</p><div className="weekly-progress"><span style={{width: `${Math.min(100, weekly / data.settings.weeklyGoal * 100)}%`}}/></div></aside></div></Page>
}
function CheckMark() {return <svg width="14" height="14" viewBox="0 0 16 16" fill="none" aria-hidden><path d="m3 8 3 3 7-7" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/></svg>}
function Stat({icon, label, value, suffix, detail}: {icon: React.ReactNode; label: string; value: string; suffix?: string; detail: string}) {return <div className="stat-card bgp-readout"><div className="row"><span className="stat-icon">{icon}</span><span>{label}</span></div><strong>{value}<small>{suffix}</small></strong><p>{detail}</p></div>}
