import {BookOpen, ChevronDown, FolderOpen, Layers3, Search, Shuffle} from 'lucide-react'
import {useMemo, useState} from 'react'
import type {Bootstrap, LibraryQuiz} from '../shared/schema'
import {latestOutcomes} from '../shared/study'
import {Empty, Page, Pill, QuizCard} from './ui'
export function LibraryPage({data, initialCategory, onStart, onMixed, onChoose, onReveal}: {data: Bootstrap; initialCategory?: string; onStart: (q: LibraryQuiz) => void; onMixed: (keys: string[]) => void; onChoose: () => void; onReveal: () => void}) {
 const [category, setCategory] = useState(initialCategory || 'all'), [unit, setUnit] = useState('all'), [search, setSearch] = useState('')
 const latest = useMemo(() => latestOutcomes(data.attempts), [data.attempts])
 const groups = data.library.categories.filter(c => category === 'all' || c.id === category).flatMap(c => c.units.filter(u => unit === 'all' || `${c.id}/${u.id}` === unit).map(u => ({c, u, quizzes: u.quizzes.filter(q => `${q.title} ${q.description} ${q.tags.join(' ')} ${u.title}`.toLowerCase().includes(search.toLowerCase()))}))).filter(g => g.quizzes.length || (!search && g.u.quizzes.length === 0))
 return <Page><div className="page-heading"><div><div className="eyebrow">A PLACE FOR EVERYTHING YOU’RE LEARNING</div><h1>Your library<span className="violet">.</span></h1><p>Explore a course, focus on a unit, or connect the dots with a mixed quiz.</p></div><button className="button primary" disabled={!groups.some(g => g.quizzes.length)} onClick={() => onMixed(groups.flatMap(g => g.quizzes.map(q => q.key)))}><Shuffle size={16}/>Build mixed session</button></div>
 <div className="library-toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search quizzes" placeholder="Search quizzes, units, or tags…" value={search} onChange={e => setSearch(e.target.value)}/>{search && <button aria-label="Clear search" onClick={() => setSearch('')}>×</button>}</div><div className="select-wrap"><select aria-label="Filter by unit" value={unit} onChange={e => setUnit(e.target.value)}><option value="all">All units</option>{data.library.categories.filter(c => category === 'all' || c.id === category).flatMap(c => c.units.map(u => <option key={`${c.id}/${u.id}`} value={`${c.id}/${u.id}`}>{u.title}</option>))}</select><ChevronDown size={15}/></div><button className="icon-button" title="Open library folder" aria-label="Open library folder" onClick={onReveal}><FolderOpen size={19}/></button></div>
 <div className="category-tabs"><button className={category === 'all' ? 'active' : ''} onClick={() => {setCategory('all'); setUnit('all')}}><Layers3 size={15}/>All courses</button>{data.library.categories.map(c => <button key={c.id} className={category === c.id ? 'active' : ''} onClick={() => {setCategory(c.id); setUnit('all')}}>{c.title}</button>)}</div>
 {data.library.issues.length > 0 && <details className="validation-banner"><summary>{data.library.issues.length} library {data.library.issues.length === 1 ? 'file needs' : 'files need'} attention. Valid quizzes are still available.</summary>{data.library.issues.map((i, n) => <div key={n}><strong>{i.file}</strong><pre>{i.message}</pre></div>)}</details>}
 {groups.map(({c, u, quizzes}) => {
  const items = u.quizzes.flatMap(q => q.questions.map(question => ({key: `${q.key}/${question.id}`, revision: q.revision})))
  const explored = items.filter(q => {const v = latest.get(q.key); return v && v.attempt.questions[v.index].revision === q.revision}).length
  const recalled = items.filter(q => {const v = latest.get(q.key); return v && v.attempt.questions[v.index].revision === q.revision && v.attempt.grades[v.index].correct}).length
  return <section className="unit-section" key={`${c.id}/${u.id}`}><div className="section-heading"><div className="row"><span className={`unit-icon tone-${c.color}`}><BookOpen size={19}/></span><div>{category === 'all' && <div className="eyebrow">{c.title}</div>}<h2>{u.title}</h2><p>{u.description}</p></div></div><Pill>{explored}/{items.length} explored · {recalled} recalled</Pill></div>{!u.quizzes.length && <div className="callout">No quizzes in this unit yet. Add a YAML quiz to its unit folder to begin building coverage.</div>}<div className="quiz-grid">{quizzes.map(q => <QuizCard key={q.key} quiz={q} attempts={data.attempts} onStart={onStart}/>)}</div></section>
 })}
 {!groups.length && <Empty icon={<BookOpen size={29}/>} title={search ? 'No matching quizzes' : 'Your library is waiting'} action={!search && <button className="button primary" onClick={onChoose}>Choose library folder</button>}>{search ? 'Try another search or course filter.' : 'Choose a folder containing your categories, units, and YAML quiz files.'}</Empty>}
 </Page>
}
