import {useEffect, useRef, useState} from 'react'
import {AnimatePresence, motion} from 'motion/react'
import {ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Bookmark, Check, CheckCircle2, ChevronLeft, Clock3, Flag, GripVertical, Save, X} from 'lucide-react'
import type {Answer, Attempt, Question, Response, Session, SessionQuestion} from '../shared/schema'
import {answerLabel, correctAnswer, gradeQuestion, isAnswered} from '../shared/scoring'
import {Markdown, Modal, Pill, duration, fade, typeLabel} from './ui'

export function Player({initial, bookmarks, onBookmark, onExit, onComplete, reportError, onFlushReady}: {initial: Session; bookmarks: string[]; onBookmark: (key: string) => void; onExit: (saved: Session) => void; onComplete: (attempt: Attempt) => void; reportError: (error: unknown) => void; onFlushReady: (flush: (() => Promise<void>) | null) => void}) {
 const [session, setSession] = useState(initial), [clock, setClock] = useState(Date.now()), [saveState, setSaveState] = useState('Saved locally'), [confirm, setConfirm] = useState(false), [busy, setBusy] = useState(false)
 const current = useRef(session), mountedAt = useRef(Date.now()), startingElapsed = useRef(initial.elapsedMs), enteredQuestion = useRef(Date.now()), timedOut = useRef(false), inFlight = useRef(Promise.resolve())
 const item = session.questions[session.currentIndex], q = item.question, response = session.responses[item.key]
 const isOpen = q.type === 'written' || q.type === 'code', checked = session.mode === 'practice' && !!response?.checked
 const elapsed = () => startingElapsed.current + Date.now() - mountedAt.current
 const patch = (change: Partial<Session>) => setSession(s => ({...s, ...change, updatedAt: new Date().toISOString(), elapsedMs: elapsed()}))
 const update = (value: Partial<Response>) => setSession(s => {const key = s.questions[s.currentIndex].key, previous = s.responses[key] ?? {answer: null, timeMs: 0}; const delta = Date.now() - enteredQuestion.current; enteredQuestion.current = Date.now(); return {...s, responses: {...s.responses, [key]: {...previous, ...value, timeMs: previous.timeMs + delta}}, elapsedMs: elapsed(), updatedAt: new Date().toISOString()}})
 const finish = async (value = current.current) => {
  if (busy) return; setBusy(true)
  try {await inFlight.current; const result = await window.quizmeadow.finish({...value, elapsedMs: elapsed()}); onComplete(result)} catch (e) {reportError(e); setBusy(false)}
 }
 const beginSubmit = async () => {
  setConfirm(false)
  const value = current.current, pending = value.questions.findIndex(v => (v.question.type === 'written' || v.question.type === 'code') && isAnswered(value.responses[v.key]?.answer) && value.responses[v.key]?.selfAssessment === undefined)
  if (pending >= 0) {patch({phase: 'grading', currentIndex: pending}); return}
  await finish(value)
 }
 useEffect(() => {current.current = session; setSaveState('Saving…'); const value = session; inFlight.current = inFlight.current.catch(() => {}).then(async () => {await window.quizmeadow.save(value); if (current.current.updatedAt === value.updatedAt) setSaveState('Saved locally')}).catch(e => {setSaveState('Save failed — retry by answering or exiting'); reportError(e)})}, [session])
 useEffect(() => {onFlushReady(async () => {await inFlight.current; await window.quizmeadow.save({...current.current, elapsedMs: elapsed()})}); return () => onFlushReady(null)}, [onFlushReady])
 useEffect(() => {const timer = setInterval(() => setClock(Date.now()), 1000); return () => clearInterval(timer)}, [])
 const remaining = session.deadlineAt ? Math.max(0, Date.parse(session.deadlineAt) - clock) : null
 useEffect(() => {if (remaining === 0 && session.phase === 'answering' && !timedOut.current) {timedOut.current = true; void beginSubmit()}}, [remaining, session.phase])
 const navigate = (index: number) => {const previous = current.current, key = previous.questions[previous.currentIndex].key, delta = Date.now() - enteredQuestion.current; enteredQuestion.current = Date.now(); setSession(s => ({...s, currentIndex: index, responses: s.responses[key] ? {...s.responses, [key]: {...s.responses[key], timeMs: s.responses[key].timeMs + delta}} : s.responses, updatedAt: new Date().toISOString(), elapsedMs: elapsed()}))}
 useEffect(() => {const onKey = (e: KeyboardEvent) => {if ((e.metaKey || e.ctrlKey) && e.key === 'ArrowRight') {e.preventDefault(); if (current.current.currentIndex < current.current.questions.length - 1) navigate(current.current.currentIndex + 1)} if ((e.metaKey || e.ctrlKey) && e.key === 'ArrowLeft') {e.preventDefault(); if (current.current.currentIndex > 0) navigate(current.current.currentIndex - 1)}}; window.addEventListener('keydown', onKey); return () => window.removeEventListener('keydown', onKey)}, [])
 const exit = async () => {setBusy(true); try {await inFlight.current; const saved = {...current.current, elapsedMs: elapsed()}; await window.quizmeadow.save(saved); onExit(saved)} catch (e) {reportError(e); setBusy(false)}}
 const answered = session.questions.filter(sq => isAnswered(session.responses[sq.key]?.answer)).length
 const gradingQuestions = session.questions.filter(sq => (sq.question.type === 'written' || sq.question.type === 'code') && isAnswered(session.responses[sq.key]?.answer))
 const needsGrade = gradingQuestions.filter(sq => session.responses[sq.key]?.selfAssessment === undefined)
 const navigateNextGrade = () => {const pos = gradingQuestions.findIndex(sq => sq.key === item.key), next = gradingQuestions[(pos + 1) % gradingQuestions.length]; if (next) navigate(session.questions.findIndex(sq => sq.key === next.key))}
 return <div className="player"><header className="player-header"><button className="button ghost small" onClick={exit} disabled={busy}><ChevronLeft size={17}/>Save & exit</button><div className="player-title"><strong>{session.title}</strong><span>{session.phase === 'grading' ? 'Self-assessment' : `${session.mode === 'exam' ? 'Exam' : 'Practice'} mode`} · {session.questions.reduce((n, sq) => n + sq.question.points, 0)} points</span></div><div className={`timer ${remaining !== null && remaining < 60000 ? 'urgent' : ''}`}><Clock3 size={16}/>{session.phase === 'grading' ? 'Answering complete' : duration(remaining ?? elapsed())}</div></header>
 <div className="player-progress"><motion.div animate={{width: `${answered / session.questions.length * 100}%`}}/></div>
 <div className="player-body"><div className="question-workspace"><div className="question-meta"><div className="row"><span className="eyebrow">QUESTION {session.currentIndex + 1} OF {session.questions.length}</span><Pill>{typeLabel(q.type)}</Pill><Pill tone="soft">{q.points} {q.points === 1 ? 'point' : 'points'}</Pill></div><div className="row"><button className={`icon-button ${bookmarks.includes(item.key) ? 'selected' : ''}`} title="Bookmark question" aria-label="Bookmark question" aria-pressed={bookmarks.includes(item.key)} onClick={() => onBookmark(item.key)}><Bookmark size={19} fill={bookmarks.includes(item.key) ? 'currentColor' : 'none'}/></button><button className={`icon-button ${response?.flagged ? 'selected' : ''}`} title="Flag for this session" aria-label="Flag for review" aria-pressed={!!response?.flagged} onClick={() => update({flagged: !response?.flagged})}><Flag size={18}/></button></div></div>
 <div className="question-breadcrumb">{item.categoryTitle}<span>/</span>{item.unitTitle}</div>
 <motion.div key={item.key} data-question-key={item.key} {...fade}><div className="question-prompt"><Markdown>{q.prompt.replace(/\{\{(.*?)\}\}/g, '[____]')}</Markdown></div>{session.phase === 'grading' ? <Grading question={q} response={response} onChange={ids => update({selfAssessment: ids})}/> : <><AnswerInput question={q} value={response?.answer ?? null} optionOrder={item.optionOrder} onChange={answer => update({answer})} disabled={checked || busy || remaining === 0}/><div className="confidence-panel"><span>How sure are you?</span><div className="confidence-buttons">{(['low', 'medium', 'high'] as const).map((v, i) => <button key={v} className={response?.confidence === v ? 'active' : ''} aria-pressed={response?.confidence === v} onClick={() => update({confidence: v})}><span aria-hidden="true">{i === 0 ? '○' : i === 1 ? '◐' : '●'}</span>{v === 'low' ? 'Unsure' : v === 'medium' ? 'Fairly sure' : 'Confident'}</button>)}</div></div>{checked && <PracticeFeedback item={item} response={response!} onGrade={ids => update({selfAssessment: ids})}/>}</>}</motion.div>
 <footer className="question-footer"><button className="button secondary" onClick={() => navigate(session.currentIndex - 1)} disabled={session.currentIndex === 0 || busy || session.phase === 'grading'}><ArrowLeft size={16}/>Previous</button><div className="row"><span className="save-label"><Save size={12}/>{saveState}</span>{session.phase === 'grading' ? <><button className="button secondary" onClick={navigateNextGrade}>Next response<ArrowRight size={16}/></button><button className="button primary" disabled={needsGrade.length > 0 || busy} onClick={() => finish()}>{busy ? 'Saving result…' : 'Finish & see results'}<Check size={16}/></button></> : <>{session.mode === 'practice' && !checked && <button className="button secondary" disabled={!isAnswered(response?.answer) || busy} onClick={() => update({checked: true})}>Check {isOpen ? 'response' : 'answer'}<Check size={16}/></button>}{session.currentIndex < session.questions.length - 1 ? <button className="button primary" onClick={() => navigate(session.currentIndex + 1)} disabled={busy}>Next question<ArrowRight size={16}/></button> : <button className="button primary" onClick={() => setConfirm(true)} disabled={busy}>Finish session<Check size={16}/></button>}</>}</div></footer>
 </div><aside className="question-sidebar"><div className="row spread"><strong>{session.phase === 'grading' ? 'Self-assessment' : 'Session overview'}</strong><Pill>{session.phase === 'grading' ? `${gradingQuestions.length - needsGrade.length}/${gradingQuestions.length}` : `${answered}/${session.questions.length}`}</Pill></div><p className="muted tiny">{session.phase === 'grading' ? 'Compare each response with the rubric. Award only the criteria your answer met.' : 'Jump between questions. A flag helps you find the ones worth another look.'}</p><div className="question-grid">{session.questions.map((sq, i) => {const r = session.responses[sq.key], isGradingItem = gradingQuestions.some(v => v.key === sq.key); return <button key={sq.key} disabled={session.phase === 'grading' && !isGradingItem} className={`${i === session.currentIndex ? 'current' : ''} ${isAnswered(r?.answer) ? 'answered' : ''} ${r?.flagged ? 'flagged' : ''}`} aria-label={`Question ${i + 1}${isAnswered(r?.answer) ? ', answered' : ''}${r?.flagged ? ', flagged' : ''}`} aria-current={i === session.currentIndex ? 'step' : undefined} onClick={() => navigate(i)}>{i + 1}{r?.flagged && <i/>}</button>})}</div><div className="question-legend"><span><i className="legend-answered"/>Answered</span><span><i className="legend-flagged"/>Flagged</span></div><div className="divider"/><div className="session-note"><SparkleIcon/><strong>{session.mode === 'practice' ? 'Learning happens in the gaps.' : 'Give your recall room to work.'}</strong><p>{session.mode === 'practice' ? 'Check your answer, read the explanation, and notice where your confidence differs from your understanding.' : 'Answers and explanations stay hidden until you submit. The timer keeps running if you leave.'}</p></div>{session.phase === 'answering' && <button className="button secondary full" onClick={() => setConfirm(true)} disabled={busy}>Submit session<CheckCircle2 size={16}/></button>}<p className="tiny muted keyboard-tip">⌘ ← / → to navigate<br/>Your work is saved on this Mac.</p></aside></div>
 <AnimatePresence>{confirm && <Modal title="Ready to finish?" onClose={() => setConfirm(false)}><p>You answered <strong>{answered} of {session.questions.length}</strong> questions. Unanswered questions receive zero points.</p>{session.questions.some(sq => sq.question.type === 'written' || sq.question.type === 'code') && <div className="callout">You’ll assess written and code responses against their rubrics before seeing your final score.</div>}<div className="modal-actions"><button className="button secondary" onClick={() => setConfirm(false)}>Keep working</button><button className="button primary" onClick={beginSubmit}>Submit answers<ArrowRight size={16}/></button></div></Modal>}</AnimatePresence>
 </div>
}
function SparkleIcon() {return <span className="session-note-icon">✦</span>}
function AnswerInput({question: q, value, optionOrder, onChange, disabled}: {question: Question; value: Answer; optionOrder?: string[]; onChange: (a: Answer) => void; disabled: boolean}) {
 if (q.type === 'single_choice' || q.type === 'multiple_choice') {
  const options = (optionOrder ?? q.options.map(o => o.id)).map(id => q.options.find(o => o.id === id)!)
  return <div className="answers"><p className="input-hint">{q.type === 'multiple_choice' ? `Choose all that apply.${q.partialCredit ? ' Partial credit; wrong selections reduce your score.' : ' All correct selections are required.'}` : 'Choose one answer.'}</p>{options.map((o, i) => {const selected = q.type === 'single_choice' ? value === o.id : Array.isArray(value) && value.includes(o.id); return <button className={`answer-option ${selected ? 'selected' : ''}`} key={o.id} disabled={disabled} onClick={() => onChange(q.type === 'single_choice' ? o.id : selected ? (value as string[]).filter(v => v !== o.id) : [...(Array.isArray(value) ? value : []), o.id])}><span aria-hidden="true" className={`answer-marker ${q.type === 'multiple_choice' ? 'square' : ''}`}>{selected ? <Check size={14}/> : String.fromCharCode(65 + i)}</span><Markdown compact>{o.text}</Markdown></button>})}</div>
 }
 if (q.type === 'true_false') return <div className="boolean-options">{[true, false].map(v => <button key={String(v)} className={`answer-option ${value === v ? 'selected' : ''}`} disabled={disabled} onClick={() => onChange(v)}><span aria-hidden="true" className="answer-marker">{value === v ? <Check size={14}/> : v ? 'T' : 'F'}</span>{v ? 'True' : 'False'}</button>)}</div>
 if (q.type === 'ordering') {
  const order = Array.isArray(value) ? value : optionOrder ?? q.options.map(o => o.id)
  const move = (from: number, to: number) => {if (from === to || to < 0 || to >= order.length) return; const next = [...order]; next.splice(to, 0, next.splice(from, 1)[0]); onChange(next)}
  return <div className="answers"><p className="input-hint">Drag to reorder, or use the arrow buttons.{q.partialCredit && ' Partial credit for correct positions.'}</p>{order.map((id, i) => <div className="ordering-row" key={id} draggable={!disabled} onDragStart={e => e.dataTransfer.setData('text/plain', String(i))} onDragOver={e => e.preventDefault()} onDrop={e => {e.preventDefault(); if (!disabled) move(Number(e.dataTransfer.getData('text/plain')), i)}}><GripVertical size={17} className="muted"/><span className="order-number">{i + 1}</span><Markdown compact>{q.options.find(o => o.id === id)!.text}</Markdown><div className="order-actions"><button className="icon-button" aria-label={`Move item ${i + 1} up`} disabled={disabled || i === 0} onClick={() => move(i, i - 1)}><ArrowUp size={15}/></button><button className="icon-button" aria-label={`Move item ${i + 1} down`} disabled={disabled || i === order.length - 1} onClick={() => move(i, i + 1)}><ArrowDown size={15}/></button></div></div>)}{!Array.isArray(value) && <button className="button secondary small" disabled={disabled} onClick={() => onChange(order)}>Use this order<Check size={14}/></button>}</div>
 }
 if (q.type === 'matching') {const values: Record<string, string> = Object.assign(Object.create(null), value && typeof value === 'object' && !Array.isArray(value) ? value : {}); return <div className="answers"><p className="input-hint">Match each item with its corresponding answer.</p>{q.pairs.map(p => <div className="matching-row" key={p.id}><Markdown compact>{p.left}</Markdown><ArrowRight size={16} className="muted"/><select aria-label={`Match ${p.left}`} disabled={disabled} value={values[p.id] ?? ''} onChange={e => onChange({...values, [p.id]: e.target.value})}><option value="">Choose a match…</option>{(optionOrder ?? q.pairs.map(r => r.id)).map(id => <option key={id} value={id}>{q.pairs.find(r => r.id === id)!.right}</option>)}</select></div>)}</div>}
 if (q.type === 'fill_blank') {const values: Record<string, string> = Object.assign(Object.create(null), value && typeof value === 'object' && !Array.isArray(value) ? value : {}); return <div className="answers"><p className="input-hint">Complete each missing term.</p>{q.blanks.map(b => <label className="field" key={b.id}><span>{b.id.replace(/-/g, ' ')}</span><input disabled={disabled} value={values[b.id] ?? ''} onChange={e => onChange({...values, [b.id]: e.target.value})} placeholder="Your answer…"/></label>)}</div>}
 if (q.type === 'numeric') return <label className="field numeric-field"><span>Your answer{q.unit && ` (${q.unit})`}</span><input aria-label={`Your answer${q.unit ? ` (${q.unit})` : ''}`} type="number" step="any" disabled={disabled} value={typeof value === 'number' ? value : ''} onChange={e => onChange(e.target.value === '' ? null : Number(e.target.value))} placeholder="Enter a number…"/>{q.tolerance > 0 && <small className="muted">Accepted tolerance: ±{q.tolerance}{q.unit && ` ${q.unit}`}</small>}</label>
 if (q.type === 'short_answer') return <label className="field"><span>Your answer</span><input aria-label="Your answer" disabled={disabled} value={typeof value === 'string' ? value : ''} onChange={e => onChange(e.target.value)} placeholder="Write a short answer…"/></label>
 return <label className="field"><span>{q.type === 'code' ? `Your solution · ${q.language}` : 'Your explanation'}</span><textarea aria-label={q.type === 'code' ? `Your solution · ${q.language}` : 'Your explanation'} className={q.type === 'code' ? 'code-editor' : ''} spellCheck={q.type !== 'code'} disabled={disabled} rows={q.type === 'code' ? 12 : 7} value={typeof value === 'string' ? value : ''} onChange={e => onChange(e.target.value)} placeholder={q.type === 'code' ? '// Work through your solution here…' : 'Explain your reasoning in your own words…'} onKeyDown={e => {if (q.type === 'code' && e.key === 'Tab') {e.preventDefault(); const el = e.currentTarget, start = el.selectionStart, end = el.selectionEnd; onChange(el.value.slice(0, start) + '  ' + el.value.slice(end)); requestAnimationFrame(() => {el.selectionStart = el.selectionEnd = start + 2})}}}/><small className="muted">Self-assessed against a rubric. {q.type === 'code' ? 'Code is saved as text; it is not executed.' : 'Your reasoning matters more than exact wording.'}</small></label>
}
function Rubric({question: q, selected, onChange}: {question: Extract<Question, {type: 'written' | 'code'}>; selected?: string[]; onChange: (ids: string[]) => void}) {
 const [draft, setDraft] = useState(selected ?? [])
 useEffect(() => setDraft(selected ?? []), [q.id, selected])
 return <div className="rubric"><div className="row spread"><strong>Which criteria did your answer meet?</strong><Pill>{q.rubric.filter(r => draft.includes(r.id)).reduce((n, r) => n + r.points, 0)}/{q.points} points</Pill></div>{q.rubric.map(r => <label className="rubric-row" key={r.id}><input type="checkbox" checked={draft.includes(r.id)} onChange={e => {const next = e.target.checked ? [...draft, r.id] : draft.filter(v => v !== r.id); setDraft(next); if (selected !== undefined) onChange(next)}}/><span>{r.description}</span><Pill>{r.points} pt</Pill></label>)}<button className="button secondary small" onClick={() => onChange(draft)}><Check size={14}/>{selected === undefined ? 'Confirm my self-assessment' : 'Self-assessment confirmed'}</button></div>
}
function Grading({question: q, response, onChange}: {question: Question; response?: Response; onChange: (ids: string[]) => void}) {
 if (q.type !== 'written' && q.type !== 'code') return <p>Select a written or code response from the overview.</p>
 return <div><div className="grading-answer"><div className="eyebrow">YOUR RESPONSE</div><pre>{answerLabel(q, response?.answer)}</pre></div><div className="grading-answer model"><div className="eyebrow">MODEL ANSWER</div><Markdown>{q.modelAnswer}</Markdown></div><Rubric question={q} selected={response?.selfAssessment} onChange={onChange}/>{q.explanation && <div className="explanation"><Markdown>{q.explanation}</Markdown></div>}</div>
}
function PracticeFeedback({item, response, onGrade}: {item: SessionQuestion; response: Response; onGrade: (ids: string[]) => void}) {const q = item.question, grade = gradeQuestion(item, response); return <motion.div {...fade} className={`practice-feedback ${grade.correct ? 'correct' : 'needs-work'}`}><div className="row"><CheckCircle2 size={19}/><strong>{grade.grading === 'self' ? 'Compare your response' : grade.correct ? 'That’s right.' : grade.earned > 0 ? 'You’re part of the way there.' : 'Here’s the learning opportunity.'}</strong>{grade.grading === 'automatic' && <Pill>{grade.earned}/{grade.possible} points</Pill>}</div>{grade.grading === 'self' ? <Grading question={q} response={response} onChange={onGrade}/> : <><div className="expected-answer"><div className="eyebrow">EXPECTED ANSWER</div><pre>{answerLabel(q, correctAnswer(q))}</pre></div>{q.explanation && <Markdown>{q.explanation}</Markdown>}</>}{q.sources.length > 0 && <div className="source-links">{q.sources.map(s => <button key={s.url} onClick={() => window.quizmeadow.openSource(s.url).catch(() => {})}>{s.title}<ArrowRight size={13}/></button>)}</div>}</motion.div>}
