import {useState} from 'react'
import {ArrowRight, Bookmark, CalendarClock, CheckCircle2, CircleHelp, RotateCcw, Sparkles} from 'lucide-react'
import type {Attempt, Bootstrap, LibraryQuiz, SessionQuestion} from '../shared/schema'
import {allQuizzes, latestOutcomes} from '../shared/study'
import {Empty, Feedback, Markdown, Page, Pill, Ring, formatDate, duration} from './ui'
export function currentQuestions(data: Bootstrap): SessionQuestion[] {return allQuizzes(data.library).flatMap(quiz => quiz.questions.map(question => ({key: `${quiz.key}/${question.id}`, quizKey: quiz.key, quizTitle: quiz.title, unitTitle: quiz.unitTitle, categoryTitle: quiz.categoryTitle, revision: quiz.revision, question})))}
export function reviewGroups(data: Bootstrap) {
 const items = currentQuestions(data), latest = latestOutcomes(data.attempts)
 return {
  mistakes: items.filter(q => {const outcome = latest.get(q.key); return outcome && outcome.attempt.questions[outcome.index].revision === q.revision && !outcome.attempt.grades[outcome.index].correct}),
  due: items.filter(q => data.reviews.some(r => r.questionKey === q.key && r.revision === q.revision && Date.parse(r.dueAt) <= Date.now())),
  bookmarks: items.filter(q => data.settings.bookmarks.includes(q.key))
 }
}
export function ReviewPage({data, onPractice, onBookmark}: {data: Bootstrap; onPractice: (items: SessionQuestion[], source: 'mistakes' | 'due' | 'mixed') => void; onBookmark: (key: string) => void}) {
 const [tab, setTab] = useState<'mistakes' | 'due' | 'bookmarks'>('mistakes'), [expanded, setExpanded] = useState<string | null>(null)
 const groups = reviewGroups(data), items = groups[tab], latest = latestOutcomes(data.attempts)
 return <Page><div className="page-heading"><div><div className="eyebrow">WHERE UNDERSTANDING GETS STRONGER</div><h1>Review & refine<span className="violet">.</span></h1><p>Return to the questions that matter. Make your next session count.</p></div><button className="button primary" disabled={!items.length} onClick={() => onPractice(items, tab === 'bookmarks' ? 'mixed' : tab)}><RotateCcw size={16}/>Practice {Math.min(20, items.length)} questions</button></div><div className="review-stats"><button className={`review-summary ${tab === 'mistakes' ? 'active' : ''}`} onClick={() => setTab('mistakes')}><CircleHelp size={21}/><strong>{groups.mistakes.length}</strong><span>Learning opportunities</span><p>Incorrect or partially correct latest answers</p></button><button className={`review-summary ${tab === 'due' ? 'active' : ''}`} onClick={() => setTab('due')}><CalendarClock size={21}/><strong>{groups.due.length}</strong><span>Due for a review</span><p>Scheduled from accuracy and confidence</p></button><button className={`review-summary ${tab === 'bookmarks' ? 'active' : ''}`} onClick={() => setTab('bookmarks')}><Bookmark size={21}/><strong>{groups.bookmarks.length}</strong><span>Bookmarked questions</span><p>A personal collection worth revisiting</p></button></div>
 <div className="section-heading"><h2>{tab === 'mistakes' ? 'Give these another look' : tab === 'due' ? 'Ready to bring back' : 'Saved for later'}</h2><span className="tiny muted">Current library versions only</span></div><div className="review-list">{items.map(item => {const previous = latest.get(item.key), grade = previous?.attempt.grades[previous.index]; return <article className="review-item" key={item.key}><div className="row spread"><div className="row"><span className="review-item-icon"><CircleHelp size={18}/></span><div className="review-item-content"><div className="tiny muted">{item.categoryTitle} / {item.unitTitle}</div><button className="review-question" onClick={() => setExpanded(expanded === item.key ? null : item.key)} aria-expanded={expanded === item.key}><Markdown compact>{item.question.prompt.replace(/\{\{(.*?)\}\}/g, '____')}</Markdown></button></div></div><div className="row">{grade && <Pill tone={grade.correct ? 'green' : 'amber'}>{grade.earned}/{grade.possible}</Pill>}<button className={`icon-button ${data.settings.bookmarks.includes(item.key) ? 'selected' : ''}`} aria-label="Toggle bookmark" onClick={() => onBookmark(item.key)}><Bookmark size={17} fill={data.settings.bookmarks.includes(item.key) ? 'currentColor' : 'none'}/></button></div></div>{expanded === item.key && previous && <Feedback item={previous.attempt.questions[previous.index]} attempt={previous.attempt}/>}</article>})}</div>{!items.length && <Empty icon={tab === 'bookmarks' ? <Bookmark size={29}/> : <Sparkles size={29}/>} title={tab === 'mistakes' ? 'A fresh start' : tab === 'due' ? 'Nothing due right now' : 'Keep the good questions close'}>{tab === 'mistakes' ? 'Complete a session to discover which questions deserve another look.' : tab === 'due' ? 'Reviews appear here when their scheduled date arrives. Incorrect or uncertain answers return sooner.' : 'Bookmark any question during a session to return to it here.'}</Empty>}
 </Page>
}
export function HistoryPage({data, onOpen}: {data: Bootstrap; onOpen: (a: Attempt) => void}) {
 const [filter, setFilter] = useState('all'), [search, setSearch] = useState('')
 const attempts = data.attempts.filter(a => (filter === 'all' || a.mode === filter) && `${a.title} ${a.questions.map(q => `${q.categoryTitle} ${q.unitTitle}`).join(' ')}`.toLowerCase().includes(search.toLowerCase()))
 const points = data.attempts.reduce((n, a) => n + a.earned, 0)
 return <Page><div className="page-heading"><div><div className="eyebrow">YOUR WORK, REMEMBERED</div><h1>Session history<span className="violet">.</span></h1><p>Every attempt is a record of what you knew at that moment.</p></div><Pill>{data.attempts.length} sessions · {Math.round(points)} points earned</Pill></div><div className="history-toolbar"><div className="category-tabs">{['all', 'practice', 'exam'].map(v => <button key={v} className={filter === v ? 'active' : ''} onClick={() => setFilter(v)}>{v === 'all' ? 'All sessions' : v === 'practice' ? 'Practice' : 'Exams'}</button>)}</div><input aria-label="Search attempts" className="standalone-search" placeholder="Search session history…" value={search} onChange={e => setSearch(e.target.value)}/></div>
 {attempts.length > 0 ? <div className="history-table"><div className="history-table-heading"><span>SESSION</span><span>COMPLETED</span><span>TIME</span><span>SCORE</span><span/></div>{attempts.map(a => <button className="history-row" key={a.id} onClick={() => onOpen(a)}><div className="row"><span className={`history-icon ${a.passed ? 'passed' : ''}`}><CheckCircle2 size={20}/></span><div><strong>{a.title}</strong><small>{a.mode === 'exam' ? 'Exam' : 'Practice'} · {a.questions.length} questions{a.grades.some(g => g.grading === 'self') && ' · includes self-assessment'}</small></div></div><span>{formatDate(a.completedAt)}<small>{new Date(a.completedAt).toLocaleTimeString(undefined, {hour: '2-digit', minute: '2-digit'})}</small></span><span>{duration(a.elapsedMs)}</span><div><Pill tone={a.passed ? 'green' : 'amber'}>{Math.round(a.percent)}%</Pill><small>{a.earned}/{a.possible} points</small></div><ArrowRight size={18}/></button>)}</div> : <Empty icon={<CalendarClock size={30}/>} title={search ? 'No matching sessions' : 'Your first session is ahead'}>{search ? 'Try a different search or mode filter.' : 'Complete a quiz to begin building your study history. Practice and exams are saved separately.'}</Empty>}
 </Page>
}
export function ResultPage({attempt, onBack, onRetry}: {attempt: Attempt; onBack: () => void; onRetry: () => void}) {
 const [filter, setFilter] = useState('all'), mistakes = attempt.grades.filter(g => !g.correct).length
 const automatic = attempt.grades.filter(g => g.grading === 'automatic'), self = attempt.grades.filter(g => g.grading === 'self')
 return <Page><button className="text-link back-link" onClick={onBack}>← Session history</button><section className={`result-hero ${attempt.passed ? 'passed' : ''}`}><Ring value={attempt.percent} size={130} label={`${Math.round(attempt.percent)}%`}/><div><Pill tone={attempt.passed ? 'green' : 'amber'}>{attempt.passed ? 'Pass threshold met' : 'Keep building understanding'}</Pill><h1>{attempt.passed ? 'Good work. Keep it growing.' : 'Now you know where to focus.'}</h1><h3>{attempt.title}</h3><p>{attempt.earned} of {attempt.possible} points · {attempt.questions.length} questions · {duration(attempt.elapsedMs)} · {attempt.mode} mode</p><span className="tiny muted">{new Date(attempt.completedAt).toLocaleString()} · Pass threshold {attempt.passScore}%</span></div></section><div className="result-details"><div><strong>{attempt.grades.filter(g => g.correct).length}<span>fully correct</span></strong></div><div><strong>{mistakes}<span>to revisit</span></strong></div><div><strong>{automatic.reduce((n, g) => n + g.earned, 0)} / {automatic.reduce((n, g) => n + g.possible, 0)}<span>automatic points</span></strong></div>{self.length > 0 && <div><strong>{self.reduce((n, g) => n + g.earned, 0)} / {self.reduce((n, g) => n + g.possible, 0)}<span>self-assessed points</span></strong></div>}</div><div className="section-heading"><h2>Answer review</h2><button className="button secondary small" onClick={onRetry}><RotateCcw size={15}/>Retry current version</button></div><div className="category-tabs">{['all', 'mistakes', 'flagged'].map(v => <button key={v} className={filter === v ? 'active' : ''} onClick={() => setFilter(v)}>{v === 'all' ? 'All answers' : v === 'mistakes' ? `To revisit (${mistakes})` : 'Flagged'}</button>)}</div><div className="feedback-list">{attempt.questions.filter(q => filter === 'all' || (filter === 'mistakes' ? !attempt.grades.find(g => g.key === q.key)!.correct : attempt.responses[q.key]?.flagged)).map(item => <Feedback key={item.key} item={item} attempt={attempt}/>)}</div><p className="tiny muted result-footnote">This result preserves the quiz content and scoring rules used for this attempt. Content edits affect future sessions.</p></Page>
}
